### ISSUE TITLE
UH Collect Tests

### ISSUE THREAD

**Issue by jdinan** [Sandia-OpenSHMEM/SOS#353]
User-submitted bug report:

I found three SHMEM fortran tests segfaulting SOS 1.3.2 RC: ./test_shmem_collect_01_int8.x, ./test_shmem_collect_02_int8.x, ./test_shmem_collect_03_int8.x
 
``` 
mpiexec.hydra -np 2 /nfs/openshmem-release/feature_tests/Fortran/collect/test_shmem_collect_02_int8.x
 
Program received signal SIGSEGV: Segmentation fault - invalid memory reference.
 
Backtrace for this error:
 
Program received signal SIGSEGV: Segmentation fault - invalid memory reference.
 
Backtrace for this error:
#0  0x7FEB4B274467
#0  0x7FC25B2DB467
#1  0x7FC25B2DBAAE
#2  0x7FEB4A77B66F
#2  0x7FC25A7E266F
#3  0x7FC25BAC2140
#3  0x7FEB4BA5B140
#4  0x400D9A in test_shmem_collects at test_shmem_collect_02_int8.f90:119
#4  0x400D9A in test_shmem_collects at test_shmem_collect_02_int8.f90:119
 
===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   PID 4714 RUNNING AT viper0
=   EXIT CODE: 139
=   CLEANING UP REMAINING PROCESSES
=   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES
===================================================================================
YOUR APPLICATION TERMINATED WITH THE EXIT STRING: Segmentation fault (signal 11)
This typically refers to a problem with your application.
Please see the FAQ page for debugging suggestions

...
Program terminated with signal 11, Segmentation fault.
...
(gdb) bt
#0  0x00007feb4ba5b140 in shmem_internal_collect_linear () from /usr/lib64/libsma.so.0
#1  0x0000000000400d9b in test_shmem_collects () at test_shmem_collect_02_int8.f90:119
#2  0x0000000000400fe3 in main (argc=1, argv=0x7ffc382523be) at test_shmem_collect_02_int8.f90:151
#3  0x00007feb4a767b15 in __libc_start_main () from /usr/lib64/libc.so.6
#4  0x0000000000400ad9 in _start ()
```

**Comment by jdinan** [comment]
TODO: Check whether we have coverage over collect with different sizes from each PE (either in SOS or Cray tests).  If not, we should add coverage for this usage model and not rely on UH Fortran tests (which may be deprecated along with the OpenSHMEM Fortran interfaces) for it.

**Comment by jdinan** [comment]
Details on how the tests were compiled:
```
$ oshfort -ggdb -O0 -fcray-pointer -ggdb -O0 -fcray-pointer -o test_shmem_collect_01_int8.x test_shmem_collect_01_int8.f90
 
$ gfortran --version
GNU Fortran (GCC) 4.8.5 20150623 (Red Hat 4.8.5-4)
Copyright (C) 2015 Free Software Foundation, Inc.
```
